package hxasjc.swgoh.enums;

public enum BattleUnitStateStat {
    BattleUnitStateStat_DEFAULT,
    BATTLEUNITSTATUNDEFINED,
    BATTLEUNITSTATHEALTH,
    BATTLEUNITSTATHEALTHPERCENT,
    BATTLEUNITSTATSPEEDFILL,
    BATTLEUNITSTATSPEEDFILLPERCENT,
    BATTLEUNITSTATSHIELDPERCENT
}
