package hxasjc.swgoh.enums;

public enum CampaignType {
    CampaignType_DEFAULT,
    STANDARD,
    ONBOARDING,
    CAMPAIGNEVENT,
    GUILDRAID,
    CAMPAIGNPVELIGHT,
    CAMPAIGNPVEDARK,
    CAMPAIGNPVEMODBATTLES,
    CAMPAIGNPVEHOLOCRON,
    CAMPAIGNSHIPPVE,
    TERRITORYBATTLE,
    ARCADERAIDBATTLES
}
