package hxasjc.swgoh.enums;

public enum EffectTargetUnitSelect {
    EffectTargetUnitSelect_DEFAULT,
    SELECTALL,
    SELECTEDTARGET,
    SELECTRANDOM,
    SELECTSELF,
    SELECTPREVIOUS,
    SELECTLASTREINFORCEMENT,
    SELECTLOWESTSURVIVABILITY,
    SELECTHIGHESTSURVIVABILITY,
    SELECTLEADER,
    SELECTSUPPORT,
    SELECTLASTSUMMON
}
