package hxasjc.swgoh.enums;

public enum GalacticBundleMainElementType {
    GalacticBundleMainElementType_DEFAULT,
    GALACTICBUNDLEMAINELEMENTTYPEPAGINATION,
    GALACTICBUNDLEMAINELEMENTTYPEINVENTORY,
    GALACTICBUNDLEMAINELEMENTTYPESPLIT,
    GALACTICBUNDLEMAINELEMENTTYPEHIGHTLIGHTS,
    GALACTICBUNDLEMAINELEMENTTYPEACCESS
}
