package hxasjc.swgoh.enums;

public enum GalacticBundleMainElementInventoryType {
    GalacticBundleMainElementInventoryType_DEFAULT,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPENONE,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPECHARACTERS,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPESHIPS,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPEUNITS,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPEITEMS,
    GALACTICBUNDLEMAINELEMENTINVENTORYTYPEALL
}
