package hxasjc.swgoh.enums;

public enum GameEventUiLocation {
    GameEventUILocation_DEFAULT,
    GAMEEVENTUILOCATIONTRIALS,
    GAMEEVENTUILOCATIONEVENTS,
    GAMEEVENTUILOCATIONMODS,
    GAMEEVENTUILOCATIONSHIPTRIALS,
    GAMEEVENTUILOCATIONNONE,
    GAMEEVENTUILOCATIONSEASONHUB,
    GAMEEVENTUILOCATIONCONQUEST
}
