package hxasjc.swgoh.enums;

public enum MaterialType {
    MaterialType_DEFAULT,
    CRAFTINGMATERIAL,
    XPMATERIAL,
    UNITSHARDMATERIAL,
    PROMOTIONMATERIAL,
    SKILLMATERIAL,
    SELLMATERIAL,
    SHIPXPMATERIAL,
    SHIPSKILLMATERIAL,
    STATMODSLICINGMATERIAL,
    STATMODOVERCLOCKINGMATERIAL,
    RELICMATERIAL,
    SCRAPMATERIAL,
    SCRAPSURPLUS,
    DATACRONMATERIAL
}
