package hxasjc.swgoh.enums;

public enum OmicronMode {
    OmicronMode_DEFAULT,
    ALLOMICRON,
    PVEOMICRON,
    PVPOMICRON,
    GUILDRAIDOMICRON,
    TERRITORYSTRIKEOMICRON,
    TERRITORYCOVERTOMICRON,
    TERRITORYBATTLEBOTHOMICRON,
    TERRITORYWAROMICRON,
    TERRITORYTOURNAMENTOMICRON,
    WAROMICRON,
    CONQUESTOMICRON,
    GALACTICCHALLENGEOMICRON,
    PVEEVENTOMICRON,
    TERRITORYTOURNAMENT3OMICRON,
    TERRITORYTOURNAMENT5OMICRON,
    GALACTICCHALLENGE3OMICRON,
    GALACTICCHALLENGE5OMICRON
}
