package hxasjc.swgoh.enums;

public enum RaidOutcome {
    RAIDOUTCOMEUNDEFINED,
    RAIDOUTCOMEWIN,
    RAIDOUTCOMEEXPIRED,
    RAIDOUTCOMEINPROGRESS,
    RAIDOUTCOMEABANDONED,
    RAIDOUTCOMESIMMED
}