package hxasjc.swgoh.enums;

public enum RecipeType {
    RecipeType_DEFAULT,
    RECIPEINVALID,
    RECIPEPROMOTION,
    RECIPESHIP,
    RECIPECONSUMABLE,
    RECIPECHARACTER,
    RECIPESKILL,
    RECIPEEQUIPMENT,
    RECIPEMODSLICING,
    RECIPEMATERIAL,
    RECIPERELIC,
    RECIPEDATACRON
}
