package hxasjc.swgoh.enums;

public enum TerritoryMapPhase {
    TerritoryMapPhase_DEFAULT,
    TERRITORYMAPOPTIN,
    TERRITORYMAPMATCHMAKING,
    TERRITORYMAPSETINITIALDEFENSE,
    TERRITORYMAPATTACK,
    TERRITORYMAPREVIEW,
    TERRITORYMAPEXPIRED
}
